# Generated by Django 4.1.7 on 2023-02-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("triggers", "0003_event_delay"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreateTodoAction",
            fields=[
                (
                    "action_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="triggers.action",
                    ),
                ),
            ],
            options={
                "verbose_name": "create todo action",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("triggers.action",),
        ),
        migrations.CreateModel(
            name="TodoIsCompletedEvent",
            fields=[
                (
                    "event_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="triggers.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "todo is completed event",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("triggers.event",),
        ),
        migrations.CreateModel(
            name="TodoIsImportantCondition",
            fields=[
                (
                    "condition_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="triggers.condition",
                    ),
                ),
            ],
            options={
                "verbose_name": "todo is important condition",
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("triggers.condition",),
        ),
    ]
